### Send POST request with json body
POST http://localhost:8443/generate/sql
Content-Type: application/json

{
  "$project": {
    "column0": {"$distinct": {}},
    "column1": 1,
    "column2": 1,
    "count": {
      "$count": "column1"
    }
  },
  "$from": {
    "$project": {
      "column0": {"$distinct": {}},
      "column1": "t.name",
      "column2": 1,
      "sum": {
        "$sum": [
          "column3",
          "column4"
        ]
      },
      "summary": {
        "$switch": {
          "branches": [
            {
              "case": {
                "$eq": [
                  "scores",
                  90
                ]
              },
              "then": "100 !"
            },
            {
              "case": {
                "$gte": [
                  {
                    "$avg": "scores"
                  },
                  90
                ]
              },
              "then": "Doing great!"
            },
            {
              "case": {
                "$and": [
                  {
                    "$gte": [
                      {
                        "$avg": "scores"
                      },
                      80
                    ]
                  },
                  {
                    "$lt": [
                      {
                        "$avg": "scores"
                      },
                      90
                    ]
                  }
                ]
              },
              "then": "Doing pretty well."
            }
          ],
          "default": "No scores found."
        }
      }
    },
    "$from": [
      "table1"
    ],
    "$lookup": [
      {
        "from": "table2",
        "type": "left",
        "localField": "table1.id",
        "foreignField": "table2.id"
      }
    ],
    "$match": {
      "column1" : "funCode1",
      "$or": [
        {
          "score": {
            "$gt": 70,
            "$lt": 90
          }
        },
        {
          "views": {
            "$gte": 1000
          }
        }
      ],
      "$tuple": [{"column1": "2013-01-01", "column2": "2013-12-01", "column3": "123"}, {"column1": "2013-01-03", "column2": "2013-12-03", "column3": "1233"}],
      "columnDate": {"$between": {"from": {"$parseDate": {"date": "2023-01-01", "format":  "%Y%m%d"}}, "to": {"$parseDate": {"date": "2023-12-01", "format":  "%Y%m%d"}}}}
    }
  },
  "$group": {
    "_id": [
      "column1",
      "column2"
    ]
  },
  "$sort": {
    "column1": 1,
    "column2": -1
  },
  "$limit": 100,
  "$skip": 100
}


### Send POST request with json body
POST http://localhost:8443/generate/sql
Content-Type: application/json

{
  "$project": {
    "column1": 1,
    "column2": 1,
    "sum": {
      "$sum": [
        "column3",
        "column4"
      ]
    },
    "summary": {
      "$switch": {
        "branches": [
          {
            "case": {
              "$eq": [
                "scores",
                90
              ]
            },
            "then": "100 !"
          },
          {
            "case": {
              "$gte": [
                {
                  "$avg": "scores"
                },
                90
              ]
            },
            "then": "Doing great!"
          },
          {
            "case": {
              "$and": [
                {
                  "$gte": [
                    {
                      "$avg": "scores"
                    },
                    80
                  ]
                },
                {
                  "$lt": [
                    {
                      "$avg": "scores"
                    },
                    90
                  ]
                }
              ]
            },
            "then": "Doing pretty well."
          }
        ],
        "default": "No scores found."
      }
    }
  },
  "$from": [
    "table1"
  ],
  "$lookup": [
    {
      "from": "table2",
      "type": "left",
      "localField": "table1.id",
      "foreignField": "table2.id"
    }
  ],
  "$match": {
    "column1": "funCode1",
    "$or": [
      {
        "score": {
          "$gt": 70,
          "$lt": 90
        }
      },
      {
        "views": {
          "$gte": 1000
        }
      }
    ]
  },
  "$group": {
    "_id": [
      "column1",
      "column2"
    ],
    "ct": {
      "$count": {}
    }
  },
  "$sort": {
    "column1": 1,
    "column2": -1
  },
  "$limit": 100,
  "$skip": 100
}


### Send POST request with json body
POST http://localhost:8443/generate/sql
Content-Type: application/json

{
  "$from": [
    "table1"
  ],
  "$project": {
    "total": { "$divide": [ { "$multiply": [{ "$subtract": [ { "$add": [ "price", "fee" ] }, "discount" ] }, "column1" ] }, "column2"] },
    "column1": 1,
    "column2": 1,
    "sum": {
      "$sum": [
        "column3",
        "column4"
      ]
    }
  },
  "$lookup": [
    {
      "from": "table2",
      "type": "left",
      "localField": "table1.id",
      "foreignField": "table2.id"
    }
  ],
  "$match": {
    "column1": "funCode1",
    "$or": [
      {
        "score": {
          "$gt": 70,
          "$lt": 90
        }
      },
      {
        "views": {
          "$gte": 1000
        }
      }
    ]
  },
  "$limit": 100,
  "$skip": 100
}
