/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.mesh.java-conventions")
}

dependencies {
    api("io.vertx:vertx-core:4.4.1")
    api("io.vertx:vertx-config:4.4.1")
    api("io.vertx:vertx-health-check:4.4.1")
    api("io.vertx:vertx-web:4.4.1")
    api("io.vertx:vertx-web-openapi:4.4.1")
    api("io.vertx:vertx-hazelcast:4.4.1")
    api("io.vertx:vertx-service-discovery:4.4.1")
    api("io.vertx:vertx-micrometer-metrics:4.4.1")
    api("io.vertx:vertx-opentracing:4.4.1")
    api("io.vertx:vertx-config-yaml:4.4.1")
    api("org.springframework.boot:spring-boot-starter-web:3.0.6")
    api("org.projectlombok:lombok:1.18.26")
    api("org.apache.logging.log4j:log4j-core:2.20.0")
    api("org.apache.logging.log4j:log4j-api:2.20.0")
    api("org.slf4j:slf4j-api:2.0.7")
    api("org.springframework:spring-test:6.0.8")
    api("org.springframework.boot:spring-boot-starter-test:3.0.6")
    api("org.apache.commons:commons-lang3:3.12.0")
    testImplementation("io.vertx:vertx-junit5:4.4.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.mockito:mockito-core:5.3.1")
}

description = "web-core"
