/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
//    id("com.mesh.java-conventions")
}

dependencies {
    api(project(":web-core"))
    api("net.bytebuddy:byte-buddy:1.14.4")
}

description = "mesh-web"
